# Generated by Django 5.2.1 on 2025-05-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('level', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='student_avatars/')),
                ('attendance', models.PositiveIntegerField(default=5)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
