# Generated by Django 5.2.1 on 2025-06-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
