# Generated by Django 5.2 on 2025-04-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_full_name_student_name_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
