# Generated by Django 5.2.1 on 2025-06-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('session_reminder', 'Session Reminder'), ('attendance_approved', 'Attendance Approved'), ('attendance_denied', 'Attendance Denied'), ('absent', 'Absent')], max_length=30),
        ),
    ]
