# Generated by Django 5.2.1 on 2025-06-01 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='courses/'),
            preserve_default=False,
        ),
    ]
