# Generated by Django 5.2.1 on 2025-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
        ('students', '0003_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='students.student'),
        ),
        migrations.AddField(
            model_name='session',
            name='attended',
            field=models.ManyToManyField(blank=True, related_name='attended_sessions', to='students.student'),
        ),
    ]
