# Generated by Django 5.1.7 on 2025-04-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='mohamed', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Lecturer', max_length=50),
        ),
    ]
