# Generated by Django 5.2.1 on 2025-06-03 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance'),
        ('courses', '0005_course_students_session_attended'),
        ('students', '0003_remove_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student',
        ),
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'attendance_requests',
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
